var user = {
  "login": "chwsimps",
  "id": 8864004,
  "avatar_url": "https://avatars.githubusercontent.com/u/8864004?v=2",
  "gravatar_id": "",
  "url": "https://api.github.com/users/chwsimps",
  "html_url": "https://github.com/chwsimps",
  "followers_url": "https://api.github.com/users/chwsimps/followers",
  "following_url": "https://api.github.com/users/chwsimps/following{/other_user}",
  "gists_url": "https://api.github.com/users/chwsimps/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/chwsimps/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/chwsimps/subscriptions",
  "organizations_url": "https://api.github.com/users/chwsimps/orgs",
  "repos_url": "https://api.github.com/users/chwsimps/repos",
  "events_url": "https://api.github.com/users/chwsimps/events{/privacy}",
  "received_events_url": "https://api.github.com/users/chwsimps/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Chase Simpson",
  "company": "",
  "blog": "",
  "location": "Atlanta, GA",
  "email": "chase.w.simpson1@gmail.com",
  "hireable": false,
  "bio": null,
  "public_repos": 9,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2014-09-22T16:58:11Z",
  "updated_at": "2014-10-08T17:19:25Z"
}
